from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal

Classification = Literal["candidate", "not_candidate", "needs_review"]

AGREEMENT_VERSION = "api_run_artifact_agreement.v1"
ALLOWED_CLASSIFICATIONS = {"candidate", "not_candidate", "needs_review"}


@dataclass(frozen=True, slots=True)
class ArtifactAgreementRow:
    """V1 review/export contract for a known run artifact.

    The agreement is intentionally separate from the runtime manifest. It says
    which artifacts V1 knows how to review or export; the manifest says which of
    those artifacts were actually written for a particular run.
    """

    relpath: str
    artifact_kind: str
    required: bool
    portable_classification: Classification
    export_classification: Classification
    review_required: bool
    listed_in_manifest: bool = True
    notes: str | None = None

    def __post_init__(self) -> None:
        validate_artifact_relpath(self.relpath)
        if not isinstance(self.artifact_kind, str) or not self.artifact_kind:
            raise ValueError("artifact_kind must be a non-empty string")
        if type(self.required) is not bool:
            raise TypeError("required must be a bool")
        if type(self.review_required) is not bool:
            raise TypeError("review_required must be a bool")
        if type(self.listed_in_manifest) is not bool:
            raise TypeError("listed_in_manifest must be a bool")
        validate_classification(self.portable_classification, "portable_classification")
        validate_classification(self.export_classification, "export_classification")
        if self.notes is not None and not isinstance(self.notes, str):
            raise TypeError("notes must be a string or None")

    def to_json_dict(self) -> dict[str, object]:
        return {
            "relpath": self.relpath,
            "artifact_kind": self.artifact_kind,
            "required": self.required,
            "portable_classification": self.portable_classification,
            "export_classification": self.export_classification,
            "review_required": self.review_required,
            "listed_in_manifest": self.listed_in_manifest,
            "notes": self.notes,
        }


def artifact_agreement_v1() -> tuple[ArtifactAgreementRow, ...]:
    """Return the stable V1 agreement rows in canonical order."""

    rows = (
        ArtifactAgreementRow(
            relpath="META.json",
            artifact_kind="run_meta",
            required=True,
            portable_classification="candidate",
            export_classification="candidate",
            review_required=True,
            notes="run metadata; review before export",
        ),
        ArtifactAgreementRow(
            relpath="config/logging.json",
            artifact_kind="logging_config",
            required=True,
            portable_classification="candidate",
            export_classification="candidate",
            review_required=True,
            notes="logging configuration snapshot; review before export",
        ),
        ArtifactAgreementRow(
            relpath="artifacts/solver_report.json",
            artifact_kind="solver_report",
            required=False,
            portable_classification="candidate",
            export_classification="candidate",
            review_required=True,
            notes="stable-readable SolverReport sidecar; review before export",
        ),
        ArtifactAgreementRow(
            relpath="artifacts/run_artifacts_manifest.json",
            artifact_kind="run_artifacts_manifest",
            required=True,
            portable_classification="candidate",
            export_classification="candidate",
            review_required=True,
            listed_in_manifest=False,
            notes="manifest generated by the run; not listed as its own input row",
        ),
    )
    validate_artifact_agreement_rows(rows)
    return rows


def manifest_agreement_rows_v1() -> tuple[ArtifactAgreementRow, ...]:
    """Agreement rows that may appear as rows in run_artifacts_manifest.json."""

    return tuple(row for row in artifact_agreement_v1() if row.listed_in_manifest)


def agreement_row_by_kind_v1() -> dict[str, ArtifactAgreementRow]:
    return {row.artifact_kind: row for row in artifact_agreement_v1()}


def agreement_manifest_row_by_kind_v1() -> dict[str, ArtifactAgreementRow]:
    return {row.artifact_kind: row for row in manifest_agreement_rows_v1()}


def assert_manifest_row_allowed_v1(
    *,
    relpath: str,
    artifact_kind: str,
    portable_classification: str,
    export_classification: str,
) -> None:
    """Validate that a manifest row matches the V1 agreement."""

    rows = agreement_manifest_row_by_kind_v1()
    row = rows.get(artifact_kind)
    if row is None:
        raise ValueError(f"manifest artifact kind is not in the V1 agreement: {artifact_kind}")
    if relpath != row.relpath:
        raise ValueError(
            f"manifest relpath for {artifact_kind} must be {row.relpath!r}, got {relpath!r}"
        )
    if portable_classification != row.portable_classification:
        raise ValueError(
            f"manifest portable_classification for {artifact_kind} must be "
            f"{row.portable_classification!r}, got {portable_classification!r}"
        )
    if export_classification != row.export_classification:
        raise ValueError(
            f"manifest export_classification for {artifact_kind} must be "
            f"{row.export_classification!r}, got {export_classification!r}"
        )


def validate_artifact_agreement_rows(rows: Iterable[ArtifactAgreementRow]) -> None:
    relpaths: set[str] = set()
    artifact_kinds: set[str] = set()
    for row in rows:
        if not isinstance(row, ArtifactAgreementRow):
            raise TypeError(f"agreement rows must be ArtifactAgreementRow, got {type(row).__name__}")
        if row.relpath in relpaths:
            raise ValueError(f"duplicate artifact agreement relpath: {row.relpath}")
        relpaths.add(row.relpath)
        if row.artifact_kind in artifact_kinds:
            raise ValueError(f"duplicate artifact agreement artifact_kind: {row.artifact_kind}")
        artifact_kinds.add(row.artifact_kind)


def classify_unregistered_artifact_path_v1(relpath: str) -> Classification:
    """Classify a path that is not part of the small V1 review/export agreement."""

    validate_artifact_relpath(relpath)
    parts = Path(relpath).parts
    prefixes = {"logs", "trace", "cache", "caches", "assets", "output"}
    if parts and parts[0] in prefixes:
        return "not_candidate"
    if relpath.endswith((".bin", ".npy", ".npz", ".zst", ".zip", ".sqlite", ".db")):
        return "not_candidate"
    return "needs_review"


def validate_artifact_relpath(relpath: str) -> None:
    if not isinstance(relpath, str) or not relpath:
        raise ValueError("relpath must be a non-empty string")
    if "\\" in relpath:
        raise ValueError("relpath must use POSIX separators")
    if relpath.startswith("/"):
        raise ValueError("relpath must be run-relative and stay under run_dir")
    path = Path(relpath)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError("relpath must be run-relative and stay under run_dir")


def validate_classification(value: str, field_name: str) -> None:
    if value not in ALLOWED_CLASSIFICATIONS:
        raise ValueError(f"{field_name} must be one of {sorted(ALLOWED_CLASSIFICATIONS)}")


__all__ = [
    "AGREEMENT_VERSION",
    "ALLOWED_CLASSIFICATIONS",
    "ArtifactAgreementRow",
    "artifact_agreement_v1",
    "manifest_agreement_rows_v1",
    "agreement_row_by_kind_v1",
    "agreement_manifest_row_by_kind_v1",
    "assert_manifest_row_allowed_v1",
    "validate_artifact_agreement_rows",
    "classify_unregistered_artifact_path_v1",
    "validate_artifact_relpath",
    "validate_classification",
]
