"""Word-structured n-gram Hamming coherence helpers."""

from rune_decrypter_prime.scoring.ngram_hamming.reference import (
    PhraseEntry,
    PhraseHit,
    PhraseProfile,
    ReferenceScanResult,
    parse_flat_token_ids,
    parse_positive_int_ids,
    validate_candidate_tokens,
    parse_word_token_ids,
    scan_chunk_reference,
)
from rune_decrypter_prime.scoring.ngram_hamming.fast_backend import (
    fast_ngram_hamming_available,
    scan_chunk_fast,
)
from rune_decrypter_prime.scoring.ngram_hamming.bridge import (
    CANDIDATE_SUMMARY_REQUIRED_FIELDS,
    CLUSTER_ROW_REQUIRED_FIELDS,
    NgramProfileSpec,
    PAIR_LEDGER_REQUIRED_FIELDS,
    PhraseCluster,
    PROFILE_MANIFEST_REQUIRED_FIELDS,
    ZERO_HIT_AUDIT_REQUIRED_FIELDS,
    bridge_profile_specs,
    canonical_profile_specs,
    cluster_hits_overlap_touch,
    cluster_rows,
    candidate_summary_rows,
    profile_manifest_hash,
    profile_manifest_rows,
    pair_ledger_row,
    score_candidate_profile_ids,
    validate_pair_ledger_row,
    validate_zero_hit_audit_row,
    zero_hit_audit_row,
)

__all__ = [
    "PhraseEntry",
    "PhraseHit",
    "PhraseProfile",
    "ReferenceScanResult",
    "parse_flat_token_ids",
    "parse_positive_int_ids",
    "validate_candidate_tokens",
    "parse_word_token_ids",
    "scan_chunk_reference",
    "fast_ngram_hamming_available",
    "scan_chunk_fast",
    "CANDIDATE_SUMMARY_REQUIRED_FIELDS",
    "CLUSTER_ROW_REQUIRED_FIELDS",
    "NgramProfileSpec",
    "PAIR_LEDGER_REQUIRED_FIELDS",
    "PhraseCluster",
    "PROFILE_MANIFEST_REQUIRED_FIELDS",
    "ZERO_HIT_AUDIT_REQUIRED_FIELDS",
    "bridge_profile_specs",
    "canonical_profile_specs",
    "cluster_hits_overlap_touch",
    "cluster_rows",
    "candidate_summary_rows",
    "profile_manifest_hash",
    "profile_manifest_rows",
    "pair_ledger_row",
    "score_candidate_profile_ids",
    "validate_pair_ledger_row",
    "validate_zero_hit_audit_row",
    "zero_hit_audit_row",
]
